FROM node:20-alpine AS builder
WORKDIR /src
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
COPY tsconfig.json ./
COPY src ./src
RUN pnpm run build

FROM node:20-alpine
WORKDIR /src
COPY --from=builder /src/node_modules ./node_modules
COPY --from=builder /src/dist ./dist
EXPOSE 3000
CMD ["node", "dist/server.js"]
